# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipe.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
                ('quantity', models.CharField(help_text='\uc7ac\ub8cc\ub7c9: \ud3ec\uae30, \uac1c, \uacf5\uae30', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\ub808\uc2dc\ud53c \uc124\uba85')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('foodname', models.CharField(max_length=200, verbose_name='\uc74c\uc2dd \uc774\ub984')),
                ('titleimage', recipe.fields.ThumbnailImageField(upload_to='photo/%Y/%m')),
                ('servings', models.IntegerField(default=1, help_text='\uc778\ubd84', verbose_name='\uc870\ub9ac\ubd84\ub7c9')),
                ('cookingtime', models.IntegerField(default=1, help_text='\ubd84', verbose_name='\uc870\ub9ac\uc2dc\uac04(\ubd84)')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('viewcount', models.IntegerField(default=0)),
                ('scraps', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipe_posts',
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Recipeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', recipe.fields.ThumbnailImageField(upload_to='photo/%Y/%m')),
                ('description', models.TextField(blank=True, verbose_name='Recipe Description')),
                ('recipeinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='foodinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
