# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0004_auto_20170603_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyTipScrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeScrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('recipefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe')),
            ],
        ),
    ]
