# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_homevisitorsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevisitorsrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
