# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_auto_20170612_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevisitorsrecord',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
