# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import honeytip.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honeyimage', honeytip.fields.ThumbnailImageField(upload_to='honeytip/content/%y/%m/%d')),
                ('honeydescription', models.TextField(blank=True, verbose_name='honeytip Description')),
            ],
        ),
        migrations.CreateModel(
            name='HoneyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('titleimage', honeytip.fields.ThumbnailImageField(upload_to='honeytip/titleiamge/%y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('viewcount', models.IntegerField(default=0)),
                ('scraps', models.IntegerField(default=0)),
                ('app_name', models.CharField(default='HoneyTip', max_length=20, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'honeytip_posts',
                'verbose_name': 'honeytip',
                'verbose_name_plural': 'honeytips',
            },
        ),
        migrations.AddField(
            model_name='contents',
            name='honeycontents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honeytip.HoneyTip'),
        ),
    ]
