# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeytip', '0002_remove_honeytip_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeytip',
            name='slug',
            field=models.SlugField(help_text='one word for title alias.', verbose_name='SLUG'),
        ),
    ]
