# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeytip', '0003_auto_20170606_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='honeydescription',
            field=models.TextField(blank=True, verbose_name='honeydescription'),
        ),
        migrations.AlterField(
            model_name='honeytip',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
        ),
        migrations.AlterField(
            model_name='honeytip',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
